import { PageShell } from "@/components/PageShell";

const Terms = () => (
  <PageShell
    title="Terms of Service"
    description="The terms and conditions for using CoreAI — a free AI chatbot and study assistant."
  >
    <article className="prose prose-neutral dark:prose-invert max-w-none">
      <h1>Terms of Service</h1>
      <p>Last updated: {new Date().toLocaleDateString()}</p>

      <h2>Acceptance</h2>
      <p>By using CoreAI you agree to these Terms. If you do not agree, please do not use the service.</p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Do not use CoreAI for illegal activity, harassment or generating harmful content.</li>
        <li>Do not attempt to reverse-engineer or abuse the service.</li>
        <li>Respect rate limits and fair-use policies.</li>
      </ul>

      <h2>AI-generated content</h2>
      <p>
        Responses are generated by AI models and may contain mistakes. Always verify important
        information independently. CoreAI is not liable for decisions made based on AI output.
      </p>

      <h2>Account termination</h2>
      <p>We may suspend accounts that violate these Terms.</p>

      <h2>Changes</h2>
      <p>We may update these Terms; continued use means you accept the new version.</p>
    </article>
  </PageShell>
);

export default Terms;
